import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProvider from "@/context/ThemeContext"; // Assuming the theme context is defined in "../context/ThemeContext"
import NavMenu from "@/components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="transition-all">
				<ThemeProvider>
					<NavMenu />
					<div className="bg-neutral-50 dark:bg-neutral-1000 min-h-screen  duration-200">
						<main className="container mt-28">{children}</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
